/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { SecureVoting, SecureVotingInterface } from "../SecureVoting.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "ballotHash",
        "type": "bytes32"
      }
    ],
    "name": "BallotSubmitted",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "electionHash",
        "type": "bytes32"
      }
    ],
    "name": "ElectionCreated",
    "type": "event"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "resultHash",
        "type": "bytes32"
      }
    ],
    "name": "ResultPublished",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "",
        "type": "bytes32"
      }
    ],
    "name": "ballotHashes",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "electionHash",
        "type": "bytes32"
      }
    ],
    "name": "createElection",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "elections",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "company",
        "type": "address"
      },
      {
        "internalType": "bytes32",
        "name": "electionHash",
        "type": "bytes32"
      },
      {
        "internalType": "bytes32",
        "name": "resultHash",
        "type": "bytes32"
      },
      {
        "internalType": "bool",
        "name": "closed",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "resultHash",
        "type": "bytes32"
      }
    ],
    "name": "publishResult",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "ballotHash",
        "type": "bytes32"
      }
    ],
    "name": "submitBallot",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b5061036b8061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610055575f3560e01c80630b150e00146100595780635e6fef011461006e5780636d980419146100ee578063787fa7be14610101578063b8dfd66914610133575b5f5ffd5b61006c6100673660046102fe565b610146565b005b6100b761007c36600461031e565b5f602081905290815260409020805460018201546002830154600384015460049094015492936001600160a01b039092169290919060ff1685565b604080519586526001600160a01b0390941660208601529284019190915260608301521515608082015260a0015b60405180910390f35b61006c6100fc3660046102fe565b6101a5565b61012361010f36600461031e565b60016020525f908152604090205460ff1681565b60405190151581526020016100e5565b61006c6101413660046102fe565b61024a565b5f828152602081815260409182902060038101849055600401805460ff1916600117905581518481529081018390527f083f8b20bac6a8289fd973242ba485b712bdbc07da6c465ed7e3995649af23fa91015b60405180910390a15050565b5f8181526001602052604090205460ff16156101fa5760405162461bcd60e51b815260206004820152601060248201526f111d5c1b1a58d85d194818985b1b1bdd60821b604482015260640160405180910390fd5b5f81815260016020818152604092839020805460ff191690921790915581518481529081018390527fdf64fef5947496f3eeb63b4b4feea2b1322324a4fc4b0a3de1fba0a10d3a30e19101610199565b6040805160a0810182528381523360208083019182528284018581525f6060850181815260808601828152898352828552918790209551865593516001860180546001600160a01b0319166001600160a01b03909216919091179055905160028501559151600384015590516004909201805460ff19169215159290921790915581518481529081018390527fe2363988d6ce7eff8c526836fec08ee2162d5dd2ce672d06748c6dde5bf9986a9101610199565b5f5f6040838503121561030f575f5ffd5b50508035926020909101359150565b5f6020828403121561032e575f5ffd5b503591905056fea2646970667358221220a0a6515e858c375e76da3c3cd52442263a9ca8a6271242748ef8d03c2380b5bf64736f6c634300081c0033";

  
      type SecureVotingConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: SecureVotingConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class SecureVoting__factory extends ContractFactory {
    
      constructor(...args: SecureVotingConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<SecureVoting & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): SecureVoting__factory {
      return super.connect(runner) as SecureVoting__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): SecureVotingInterface {
      return new Interface(_abi) as SecureVotingInterface;
    }
    
    override attach(address: string | Addressable): SecureVoting {
      return super.attach(address) as SecureVoting;
    }
  static connect(address: string, runner?: ContractRunner | null): SecureVoting {
      return new Contract(address, _abi, runner) as unknown as SecureVoting;
    }
  }

  
  