/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface SecureVotingInterface extends Interface {
    getFunction(nameOrSignature: "ballotHashes" | "createElection" | "elections" | "publishResult" | "submitBallot"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BallotSubmitted" | "ElectionCreated" | "ResultPublished"): EventFragment;

    encodeFunctionData(functionFragment: 'ballotHashes', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'createElection', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'elections', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'publishResult', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'submitBallot', values: [BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'ballotHashes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'elections', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishResult', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submitBallot', data: BytesLike): Result;
  }

  
    export namespace BallotSubmittedEvent {
      export type InputTuple = [electionId: BigNumberish, ballotHash: BytesLike];
      export type OutputTuple = [electionId: bigint, ballotHash: string];
      export interface OutputObject {electionId: bigint, ballotHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionCreatedEvent {
      export type InputTuple = [electionId: BigNumberish, electionHash: BytesLike];
      export type OutputTuple = [electionId: bigint, electionHash: string];
      export interface OutputObject {electionId: bigint, electionHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ResultPublishedEvent {
      export type InputTuple = [electionId: BigNumberish, resultHash: BytesLike];
      export type OutputTuple = [electionId: bigint, resultHash: string];
      export interface OutputObject {electionId: bigint, resultHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface SecureVoting extends BaseContract {
    
    connect(runner?: ContractRunner | null): SecureVoting;
    waitForDeployment(): Promise<this>;

    interface: SecureVotingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ballotHashes: TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    createElection: TypedContractMethod<
      [electionId: BigNumberish, electionHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    elections: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, boolean] & {electionId: bigint, company: string, electionHash: string, resultHash: string, closed: boolean }],
      'view'
    >
    

    
    publishResult: TypedContractMethod<
      [electionId: BigNumberish, resultHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    submitBallot: TypedContractMethod<
      [electionId: BigNumberish, ballotHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ballotHashes'): TypedContractMethod<
      [arg0: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'createElection'): TypedContractMethod<
      [electionId: BigNumberish, electionHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'elections'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, boolean] & {electionId: bigint, company: string, electionHash: string, resultHash: string, closed: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'publishResult'): TypedContractMethod<
      [electionId: BigNumberish, resultHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submitBallot'): TypedContractMethod<
      [electionId: BigNumberish, ballotHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'BallotSubmitted'): TypedContractEvent<BallotSubmittedEvent.InputTuple, BallotSubmittedEvent.OutputTuple, BallotSubmittedEvent.OutputObject>;
getEvent(key: 'ElectionCreated'): TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
getEvent(key: 'ResultPublished'): TypedContractEvent<ResultPublishedEvent.InputTuple, ResultPublishedEvent.OutputTuple, ResultPublishedEvent.OutputObject>;

    filters: {
      
      'BallotSubmitted(uint256,bytes32)': TypedContractEvent<BallotSubmittedEvent.InputTuple, BallotSubmittedEvent.OutputTuple, BallotSubmittedEvent.OutputObject>;
      BallotSubmitted: TypedContractEvent<BallotSubmittedEvent.InputTuple, BallotSubmittedEvent.OutputTuple, BallotSubmittedEvent.OutputObject>;
    

      'ElectionCreated(uint256,bytes32)': TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
      ElectionCreated: TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
    

      'ResultPublished(uint256,bytes32)': TypedContractEvent<ResultPublishedEvent.InputTuple, ResultPublishedEvent.OutputTuple, ResultPublishedEvent.OutputObject>;
      ResultPublished: TypedContractEvent<ResultPublishedEvent.InputTuple, ResultPublishedEvent.OutputTuple, ResultPublishedEvent.OutputObject>;
    
    };
  }